name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cpp unit
      run: sudo apt install -y libcppunit-dev
    - name: install clang compiler
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: executing .cpp files
      run: clang++ tests_mylib.cpp | 
        ./a.out
      
      
    
